# Generated by Django 6.0 on 2025-12-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Party',
        ),
    ]
