# Generated by Django 6.0 on 2025-12-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='login_type',
            field=models.CharField(blank=True, default='email', max_length=50, null=True),
        ),
    ]
