# Generated by Django 6.0 on 2026-01-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_product_product_img_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.CharField(default='Default Customer', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='credit_card', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
